import status from './status'

const BASE = {
  CREATE_ORGANIZATION: 'CREATE_ORGANIZATION',
  FIND_ORGANIZATIONS: 'FIND_ORGANIZATIONS',
  GET_ORGANIZATION: 'GET_ORGANIZATION',
  PATCH_ORGANIZATION: 'PATCH_ORGANIZATION',
  REMOVE_ORGANIZATION: 'REMOVE_ORGANIZATION',
  UPDATE_ORGANIZATION: 'UPDATE_ORGANIZATION',
}

const ERROR = {
  CREATE_ORGANIZATION: BASE.CREATE_ORGANIZATION+status.ERROR,
  FIND_ORGANIZATION: BASE.FIND_ORGANIZATION+status.ERROR,
  GET_ORGANIZATION: BASE.GET_ORGANIZATION+status.ERROR,
  PATCH_ORGANIZATION: BASE.PATCH_ORGANIZATION+status.ERROR,
  REMOVE_ORGANIZATION: BASE.REMOVE_ORGANIZATION+status.ERROR,
  UPDATE_ORGANIZATION: BASE.UPDATE_ORGANIZATION+status.ERROR,
}

const SUCCESS = {
  CREATE_ORGANIZATION: BASE.CREATE_ORGANIZATION+status.SUCCESS,
  FIND_ORGANIZATION: BASE.FIND_ORGANIZATION+status.SUCCESS,
  GET_ORGANIZATION: BASE.GET_ORGANIZATION+status.SUCCESS,
  PATCH_ORGANIZATION: BASE.PATCH_ORGANIZATION+status.SUCCESS,
  REMOVE_ORGANIZATION: BASE.REMOVE_ORGANIZATION+status.SUCCESS,
  UPDATE_ORGANIZATION: BASE.UPDATE_ORGANIZATION+status.SUCCESS,
}



export default {
  BASE,
  ERROR,
  SUCCESS,
}