import status from './status'

const BASE = {
	CREATE_USER: 'CREATE_USER',
	FIND_USERS: 'FIND_USERS',
	GET_USER: 'GET_USER',
	PATCH_USER: 'PATCH_USER',
	REMOVE_USER: 'REMOVE_USER',
	UPDATE_USER: 'UPDATE_USER',
}

const ERROR = {
	CREATE_USER: BASE.CREATE_USER+status.ERROR,
	FIND_USER: BASE.FIND_USER+status.ERROR,
	GET_USER: BASE.GET_USER+status.ERROR,
	PATCH_USER: BASE.PATCH_USER+status.ERROR,
	REMOVE_USER: BASE.REMOVE_USER+status.ERROR,
	UPDATE_USER: BASE.UPDATE_USER+status.ERROR,
}

const SUCCESS = {
	CREATE_USER: BASE.CREATE_USER+status.SUCCESS,
	FIND_USER: BASE.FIND_USER+status.SUCCESS,
	GET_USER: BASE.GET_USER+status.SUCCESS,
	PATCH_USER: BASE.PATCH_USER+status.SUCCESS,
	REMOVE_USER: BASE.REMOVE_USER+status.SUCCESS,
	UPDATE_USER: BASE.UPDATE_USER+status.SUCCESS,
}



export default {
	BASE,
	ERROR,
	SUCCESS,
}